stages:
  data_ingestion:
    cmd: python src/DocumindAI/ml_pipeline/stage_01_data_ingestion.py
    deps:
      - src/DocumindAI/ml_pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dataset_new


  data_validation:
    cmd: python src/DocumindAI/ml_pipeline/stage_02_data_validation.py
    deps:
      - src/DocumindAI/ml_pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset_new
    outs:
      - artifacts/data_validation


  data_preprocessing:
    cmd: python src/DocumindAI/ml_pipeline/stage_03_data_preprocessing.py
    deps:
      - src/DocumindAI/ml_pipeline/stage_03_data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/dataset_new
    params:
      - preprocessing.max_length
      - preprocessing.training_ratio
      - preprocessing.batch_size
    outs:
      - artifacts/data_preprocessing/encoded_data
      - artifacts/data_preprocessing/preprocessor
      - artifacts/data_preprocessing/raw_dataset


  model_trainer:
    cmd: python src/DocumindAI/ml_pipeline/stage_04_model_trainer.py
    deps:
      - src/DocumindAI/ml_pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_preprocessing/encoded_data
    params:
      - TrainingArguments.num_labels
      - TrainingArguments.num_train_epochs
      - TrainingArguments.per_device_train_batch_size
      - TrainingArguments.per_device_eval_batch_size
      - TrainingArguments.gradient_accumulation_steps
      - TrainingArguments.learning_rate
      - TrainingArguments.weight_decay
      - TrainingArguments.eval_strategy
      - TrainingArguments.save_strategy
      - TrainingArguments.load_best_model_at_end
      - TrainingArguments.remove_unused_columns
      - TrainingArguments.optim
      - TrainingArguments.number_of_unfreeze_layers   
    outs:
      - artifacts/model_trainer/documind_model     


  model_evaluation:
    cmd: python src/DocumindAI/ml_pipeline/stage_05_model_evaluation.py
    deps:
      - src/DocumindAI/ml_pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_preprocessing/encoded_data
      - artifacts/model_trainer/documind_model
    params:
      - params.yaml
    metrics:
    - metrics.json:
        cache: false